services:
  postgres:
    hostname: postgres_server
    image: postgis/postgis:16-3.4
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres_username
      - POSTGRES_DB=postgres_database

  base-django:
    build: .
    restart: always
    volumes:
      - .:/code:cached
    env_file:
      - base.env

  django:
    hostname: web_server
    extends: base-django
    command: python manage.py runserver_plus 0.0.0.0:8000
    ports:
      - 8000:8000
